import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import "react-quill/dist/quill.snow.css";
import { ChakraUIProvider } from "../_shared/lib/chakra-ui/ChakraUIProvider";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className + " absolute w-full h-full"}
        suppressHydrationWarning={true}
      >
        <ChakraUIProvider>{children}</ChakraUIProvider>
      </body>
    </html>
  );
}
