import { Avatar } from "@chakra-ui/react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import DrawerButton from "./_shared/components/DrawerButton";
import SearchInput from "./_shared/components/SearchInput";
import { ChakraUIProvider } from "./_shared/lib/chakra-ui/ChakraUIProvider";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " absolute w-full h-full"}>
        <ChakraUIProvider>
          <div className="w-full top-0 sticky p-3 flex items-center justify-between ml-auto border-b">
            <DrawerButton />
            <SearchInput />
            <Avatar
              size="md"
              name="Dan Abrahmov"
              src="https://bit.ly/dan-abramov"
            />
          </div>
          {children}
        </ChakraUIProvider>
      </body>
    </html>
  );
}
